### ISSUE TITLE
TP-final--

### ISSUE THREAD

**Issue by pipolag22** [santiagosilvestrini/git-github-tp-final-2023#36]
issue.. creado por jorge bellerate #36

**Comment by pipolag22** [comment]
.

**Comment by santiagosilvestrini** [comment]
Hola Jorge @pipolag22, no veo tu Pull Request. Te extiendo la entrega hasta Martes 14 al final del día. Avisame si necesitás ayuda.

**Comment by pipolag22** [comment]
[image: image.png]   hola! la hice pero me quedo como closed.  lo hago
nuevamente?

**Comment by pipolag22** [comment]
me quedo como closed.  lo hago nuevamente? 
![image](https://github.com/santiagosilvestrini/git-github-tp-final-2023/assets/112628139/a85821c1-9be3-4e74-b665-e8fccb168460)

**Comment by santiagosilvestrini** [comment]
Reabrilo o creá otro. Aprovechá y ponele el comentario a este Issue así quedan enlazados.

**Comment by pipolag22** [comment]
quedo ahi?

**Comment by santiagosilvestrini** [comment]
Si, ahora veo el PR abierto. 2 comentarios para que tengas en cuenta:
1: En el PR podés poner un comentario con el número de este Issue #36, para que queden enlazados 
2: Ojo que por lo que veo usaste VSCode, y se subieron carpetas propias del IDE (para que esto no suceda deberías incluir el path de esa carpeta en el .gitignore)
![image](https://github.com/santiagosilvestrini/git-github-tp-final-2023/assets/2256587/8f99297a-68c5-4c50-bd8d-3b859ec77f21)

**Comment by pipolag22** [comment]
graciasss
